### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by alphapapa** [faissaloo/Oven#2]
Hi,

You may or may not be interested, but since you seem kind of new to Python, I thought I would show you some things you could do to make your code more "Pythonic" and easier to read.  I put it in a gist: https://gist.github.com/alphapapa/1c2ff18017b46f4b9761

**Comment by faissaloo** [comment]
Doesn't the way line 60-61 is split up violate PEP8?

**Comment by alphapapa** [comment]
Well, flycheck-mode in Emacs doesn't flag it as a PEP8 violation, and it's using pep8 or flake8 to check, so I think it's compliant.  It does flag it if the line is too long, though.

The most important things to notice are, e.g. the way I changed the directory-checking to reduce redundancy, using `os.path.join` and `os.path.isdir, and making a function to do the timestamped printing.  Even better is to use `logging`, which makes it even simpler.

**Comment by faissaloo** [comment]
I agree with your improvements, they're very good, could you make a pull request?

**Comment by alphapapa** [comment]
I'm not surprised, because I haven't actually used the script, I just modified it and checked that the syntax is valid.  :)  The way the command was being put together seemed confusing to me, so I may have broken it.  Should be easy enough to fix though.  :)

**Comment by faissaloo** [comment]
Cool, can you do that and then make a pull request?

**Comment by alphapapa** [comment]
Sorry, I'm pretty busy.  I'll leave fixing the bug as an exercise for the original author.  :)

**Comment by faissaloo** [comment]
Ok, I'll see what I can do.
